---
apiVersion: v1
kind: Secret
metadata:
  name: apt-upgrade
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    secrets=$(dirname $0)
    apt-get --assume-yes update
    apt-get --assume-yes upgrade
    if [ -f /var/run/reboot-required ]; then
      cat /var/run/reboot-required
      reboot
    fi
